MCU = atmega32u4
BOOTLOADER = atmel-dfu

BOOTMAGIC_ENABLE = yes
EXTRAKEY_ENABLE = yes
NKRO_ENABLE = yes
MOUSEKEY_ENABLE = no
COMMAND_ENABLE = no
SLEEP_LED_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
BLUETOOTH_ENABLE = no
AUDIO_ENABLE = no
NKRO_ENABLE = yes
OS_DETECTION_ENABLE = no
WPM_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
AVR_USE_MINIMAL_PRINTF = yes
MAGIC_ENABLE = no
CONSOLE_ENABLE = no

DEBOUNCE_TYPE = sym_eager_pk
LTO_ENABLE = yes
DEFAULT_FOLDER = adm42/v2


